# 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [14]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [15]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 200
np.random.seed(seed)
tf.set_random_seed(seed)

In [16]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0])
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4,)


array([0, 1, 1, 0])

In [24]:
y_data = y_data.reshape(4,1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [25]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [26]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [27]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [28]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [29]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [30]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [31]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 [None, 1.5790477]
1000 [None, 0.0025653164]
2000 [None, 0.0007466561]
3000 [None, 0.00032906426]
4000 [None, 0.00016896558]
5000 [None, 9.339053e-05]
6000 [None, 5.3645817e-05]
7000 [None, 3.150162e-05]
8000 [None, 1.8775663e-05]
9000 [None, 1.1250449e-05]
10000 [None, 6.7800547e-06]

Hypothesis:
[[8.396974e-06]
 [9.999976e-01]
 [9.999919e-01]
 [8.073839e-06]] 
Predicted:
[[0.]
 [1.]
 [1.]
 [0.]] 
Accuracy:
1.0

W1:
[[ 12.739763 -12.432982]
 [-13.275679  11.538834]] 
b1:
[-6.4501987 -6.419876 ] 
W2:
[[23.524672]
 [24.839928]]
b1:
[-11.765141]
